import type { IProduct } from "~/types"

const data = ref<IProduct[]>([
  {
    id: 1,
    image: "/images/board.webp",
    saleType: 'Аукцион',
    title: "Доска обрезная 100мм",
    city: "Московская область, Подольск",
    seller: "Торговый Дом Снаб",
    category: "Стройматериалы",
    description: "Доска обрезная: 50х100х6000 мм. Пиломатериалы 1-го сорта. Собственное производство. Гарантия качества. Низкая цена. Универсальный, экологически чистый пиломатериал с одинаковым прямоугольным сечением по всей длине. Стандартные размеры: длина может варьироваться в пределах 1–6 м с шагом 0,25 м, ширина — 75–275 мм с шагом 0,25 мм, толщина — 16, 19, 22, 25, 32, 40, 44, 50, 60 и 75 мм.",
    price: 10000,
    quantity: 3,
    isFavourites: false,
    isDeal: false,
    isStock: true,
    isPaid: false
  },
  {
    id: 2,
    image: "/images/board.webp",
    saleType: 'Аукцион',
    title: "Доска обрезная 150мм",
    city: "Московская область, Подольск",
    seller: "Торговый Дом Снаб",
    category: "Стройматериалы",
    description: "Доска обрезная: 50х100х6000 мм. Пиломатериалы 1-го сорта. Собственное производство. Гарантия качества. Низкая цена. Универсальный, экологически чистый пиломатериал с одинаковым прямоугольным сечением по всей длине. Стандартные размеры: длина может варьироваться в пределах 1–6 м с шагом 0,25 м, ширина — 75–275 мм с шагом 0,25 мм, толщина — 16, 19, 22, 25, 32, 40, 44, 50, 60 и 75 мм.",
    price: 14000,
    quantity: 4,
    isFavourites: false,
    isDeal: false,
    isStock: true,
    isPaid: false
  },
  {
    id: 3,
    image: "/images/board.webp",
    saleType: 'Аукцион',
    title: "Доска обрезная 200мм",
    city: "Московская область, Подольск",
    seller: "Торговый Дом Снаб",
    category: "Стройматериалы",
    description: "Доска обрезная: 50х100х6000 мм. Пиломатериалы 1-го сорта. Собственное производство. Гарантия качества. Низкая цена. Универсальный, экологически чистый пиломатериал с одинаковым прямоугольным сечением по всей длине. Стандартные размеры: длина может варьироваться в пределах 1–6 м с шагом 0,25 м, ширина — 75–275 мм с шагом 0,25 мм, толщина — 16, 19, 22, 25, 32, 40, 44, 50, 60 и 75 мм.",
    price: 18000,
    quantity: 5,
    isFavourites: false,
    isDeal: false,
    isStock: true,
    isPaid: false
  },
  {
    id: 4,
    image: "/images/brick.webp",
    saleType: 'Аукцион',
    title: "Кирпич керамический печной М200",
    city: "Воронеж",
    seller: "ТД СнабСервис",
    category: "Стройматериалы",
    description: "Кирпич керамический печной М200. В упаковке 100 шт. В наличии на складе. Высокое качество. Предназначен для строительства печей, каминов, дымоходов",
    price: 4000,
    quantity: 3,
    isFavourites: false,
    isDeal: false,
    isStock: true,
    isPaid: false
  },
  {
    id: 5,
    image: "/images/brick.webp",
    saleType: 'Аукцион',
    title: "Кирпич керамический печной М200",
    city: "Воронеж",
    seller: "ТД СнабСервис",
    category: "Стройматериалы",
    description: "Кирпич керамический печной М200. В упаковке 100 шт. В наличии на складе. Высокое качество. Предназначен для строительства печей, каминов, дымоходов",
    price: 3500,
    quantity: 4,
    isFavourites: false,
    isDeal: false,
    isStock: true,
    isPaid: false
  },
  {
    id: 6,
    image: "/images/brick.webp",
    saleType: 'Аукцион',
    title: "Кирпич керамический печной М200",
    city: "Воронеж",
    seller: "ТД СнабСервис",
    category: "Стройматериалы",
    description: "Кирпич керамический печной М200. В упаковке 100 шт. В наличии на складе. Высокое качество. Предназначен для строительства печей, каминов, дымоходов",
    price: 3000,
    quantity: 5,
    isFavourites: false,
    isDeal: false,
    isStock: true,
    isPaid: false
  },
  {
    id: 7,
    image: "/images/cobblestones.webp",
    saleType: 'Прямые продажи',
    title: "Брусчатка мостовая серая 60мм",
    city: "Санкт-Петербург, Красное Село",
    seller: "Торговый Дом ГОСТ",
    category: "Стройматериалы",
    description: "Брусчатка мостовая серая: 200х200х60 мм. Компактные прямоугольные плиты с ровной, гладкой текстурой. Бесплатная доставка.",
    price: 15000,
    quantity: 3,
    isFavourites: false,
    isDeal: false,
    isStock: true,
    isPaid: false
  },
  {
    id: 8,
    image: "/images/cobblestones.webp",
    saleType: 'Прямые продажи',
    title: "Брусчатка мостовая серая 70мм",
    city: "Санкт-Петербург, Красное Село",
    seller: "Торговый Дом ГОСТ",
    category: "Стройматериалы",
    description: "Брусчатка мостовая серая: 200х200х70 мм. Компактные прямоугольные плиты с ровной, гладкой текстурой. Бесплатная доставка.",
    price: 17000,
    quantity: 3,
    isFavourites: false,
    isDeal: false,
    isStock: true,
    isPaid: false
  },

  {
    id: 9,
    image: "/images/cobblestones.webp",
    saleType: 'Прямые продажи',
    title: "Брусчатка мостовая серая 80мм",
    city: "Санкт-Петербург, Красное Село",
    seller: "Торговый Дом ГОСТ",
    category: "Стройматериалы",
    description: "Брусчатка мостовая серая: 200х200х80 мм. Компактные прямоугольные плиты с ровной, гладкой текстурой. Бесплатная доставка.",
    price: 21000,
    quantity: 3,
    isFavourites: false,
    isDeal: false,
    isStock: true,
    isPaid: false
  },
  {
    id: 10,
    image: "/images/cobblestones.webp",
    saleType: 'Прямые продажи',
    title: "Брусчатка мостовая серая 90мм",
    city: "Санкт-Петербург, Красное Село",
    seller: "Торговый Дом ГОСТ",
    category: "Стройматериалы",
    description: "Брусчатка мостовая серая: 200х200х90 мм. Компактные прямоугольные плиты с ровной, гладкой текстурой. Бесплатная доставка.",
    price: 24000,
    quantity: 3,
    isFavourites: false,
    isDeal: false,
    isStock: true,
    isPaid: false
  }
])

export function fetchData() {
  
  return data.value
}